# Generated by Django 5.2.17 on 2026-08-13 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("primaryid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("caseid", models.BigIntegerField()),
                ("caseversion", models.IntegerField(null=True)),
                ("quarter", models.CharField(max_length=6)),
                ("fda_dt", models.DateField(null=True)),
                ("fda_dt_raw", models.CharField(max_length=16, null=True)),
                (
                    "fda_dt_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=8,
                    ),
                ),
                ("event_dt", models.DateField(null=True)),
                ("event_dt_raw", models.CharField(max_length=16, null=True)),
                (
                    "event_dt_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=8,
                    ),
                ),
                ("sex", models.CharField(max_length=8, null=True)),
                ("age_years", models.FloatField(null=True)),
                ("weight_kg", models.FloatField(null=True)),
                ("country", models.CharField(max_length=32, null=True)),
                (
                    "country_source",
                    models.CharField(
                        choices=[
                            ("occurrence", "Occurrence country"),
                            ("reporter", "Reporter country"),
                            ("none", "Neither supplied"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("occp_cod", models.CharField(max_length=16, null=True)),
                ("serious", models.BooleanField(default=False)),
                ("serious_death", models.BooleanField(default=False)),
                ("outcome_codes", models.JSONField(default=list)),
            ],
            options={
                "db_table": "faers_case",
                "ordering": ["-fda_dt", "primaryid"],
                "indexes": [
                    models.Index(fields=["quarter"], name="faers_case_quarter_idx"),
                    models.Index(fields=["fda_dt"], name="faers_case_fda_dt_idx"),
                    models.Index(fields=["caseid"], name="faers_case_caseid_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Duplicate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("primaryid", models.BigIntegerField()),
                ("canonical_primaryid", models.BigIntegerField()),
                ("method", models.CharField(max_length=32)),
                ("score", models.FloatField(null=True)),
                ("drug_jaccard", models.FloatField(null=True)),
                ("reaction_jaccard", models.FloatField(null=True)),
                ("cross_quarter", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "faers_duplicate",
                "indexes": [
                    models.Index(fields=["canonical_primaryid"], name="faers_dup_canonical_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("primaryid", "method"), name="faers_duplicate_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Indication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("indi_drug_seq", models.IntegerField(null=True)),
                ("indi_pt", models.TextField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="primaryid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications",
                        to="signals.case",
                    ),
                ),
            ],
            options={
                "db_table": "faers_indication",
            },
        ),
        migrations.CreateModel(
            name="IngestManifest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=32)),
                ("unit", models.CharField(max_length=32)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("row_count", models.BigIntegerField(default=0)),
                ("row_counts", models.JSONField(default=dict)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("had_deleted_file", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ingest_manifest",
                "ordering": ["source", "unit"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "unit"), name="ingest_manifest_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("outc_cod", models.CharField(max_length=8, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="primaryid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="signals.case",
                    ),
                ),
            ],
            options={
                "db_table": "faers_outcome",
            },
        ),
        migrations.CreateModel(
            name="Therapy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dsg_drug_seq", models.IntegerField(null=True)),
                ("start_dt", models.DateField(null=True)),
                ("start_dt_raw", models.CharField(max_length=16, null=True)),
                (
                    "start_dt_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=8,
                    ),
                ),
                ("end_dt", models.DateField(null=True)),
                ("end_dt_raw", models.CharField(max_length=16, null=True)),
                (
                    "end_dt_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        max_length=8,
                    ),
                ),
                ("dur_days", models.FloatField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="primaryid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapies",
                        to="signals.case",
                    ),
                ),
            ],
            options={
                "db_table": "faers_therapy",
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("drug_seq", models.IntegerField(null=True)),
                ("role_cod", models.CharField(max_length=8, null=True)),
                ("drugname_raw", models.TextField(null=True)),
                ("prod_ai", models.TextField(null=True)),
                ("route", models.CharField(max_length=64, null=True)),
                ("rxcui", models.CharField(max_length=16, null=True)),
                ("ingredient_rxcui", models.CharField(max_length=16, null=True)),
                ("match_method", models.CharField(max_length=32, null=True)),
                ("match_score", models.FloatField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="primaryid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="signals.case",
                    ),
                ),
            ],
            options={
                "db_table": "faers_drug",
                "indexes": [
                    models.Index(
                        fields=["ingredient_rxcui", "case"], name="faers_drug_ing_case_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pt", models.TextField(null=True)),
                ("drug_rec_act", models.TextField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        db_column="primaryid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="signals.case",
                    ),
                ),
            ],
            options={
                "db_table": "faers_reaction",
                "indexes": [models.Index(fields=["pt", "case"], name="faers_reaction_pt_case_idx")],
            },
        ),
    ]
