# Generated by Django 5.2.17 on 2026-08-13 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indication",
            name="case",
        ),
        migrations.RemoveField(
            model_name="outcome",
            name="case",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="case",
        ),
        migrations.RemoveField(
            model_name="therapy",
            name="case",
        ),
        migrations.DeleteModel(
            name="Drug",
        ),
        migrations.DeleteModel(
            name="Indication",
        ),
        migrations.DeleteModel(
            name="Outcome",
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
        migrations.DeleteModel(
            name="Therapy",
        ),
    ]
