# Generated by Django 5.2.17 on 2026-08-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0002_remove_indication_case_remove_outcome_case_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugConcept",
            fields=[
                ("ingredient_rxcui", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("tty", models.CharField(max_length=8)),
                ("atc_code", models.CharField(max_length=16, null=True)),
            ],
            options={
                "db_table": "drug_concept",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DrugStringMatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_field",
                    models.CharField(
                        choices=[
                            ("prod_ai", "Active ingredient field"),
                            ("drugname", "Drug name field"),
                        ],
                        max_length=16,
                    ),
                ),
                ("folded_string", models.TextField()),
                ("cleaned_string", models.TextField()),
                ("rxcui", models.BigIntegerField(null=True)),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("override", "Curated override"),
                            ("override_not_a_drug", "Curated: not a drug"),
                            ("exact", "Exact term match"),
                            ("approximate", "Approximate term match"),
                            ("unmatched", "No match above the floor"),
                        ],
                        max_length=24,
                    ),
                ),
                ("match_score", models.FloatField(null=True)),
                ("candidate_rank", models.IntegerField(null=True)),
                ("components_total", models.IntegerField(default=1)),
                ("components_matched", models.IntegerField(default=0)),
                ("retrieved_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drug_string_match",
                "ordering": ["source_field", "folded_string"],
                "indexes": [models.Index(fields=["match_method"], name="drug_string_method_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_field", "folded_string"), name="drug_string_match_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DrugStringIngredient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ordinal", models.IntegerField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="string_matches",
                        to="signals.drugconcept",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="signals.drugstringmatch",
                    ),
                ),
            ],
            options={
                "db_table": "drug_string_ingredient",
                "ordering": ["match", "ordinal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "ingredient"), name="drug_string_ingredient_unique"
                    )
                ],
            },
        ),
    ]
