# Generated by Django 5.2.17 on 2026-08-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("set_id", models.CharField(max_length=64, unique=True)),
                ("spl_id", models.CharField(blank=True, default="", max_length=64)),
                ("version", models.CharField(blank=True, default="", max_length=16)),
                ("effective_time", models.CharField(blank=True, default="", max_length=16)),
                ("brand_names", models.JSONField(default=list)),
                ("generic_names", models.JSONField(default=list)),
                ("substance_names", models.JSONField(default=list)),
                ("rxcuis", models.JSONField(default=list)),
                ("retrieved_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "label_document",
                "ordering": ["set_id"],
                "indexes": [
                    models.Index(fields=["effective_time"], name="label_doc_effective_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelDrugKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("folded_string", models.TextField()),
                ("query", models.TextField()),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ingredient", "RxNorm ingredient rxcui"),
                            ("cleaned_string", "Deterministically cleaned drug string"),
                            ("override", "Curated override"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ingredient_rxcui", models.BigIntegerField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_keys",
                        to="documents.labeldocument",
                    ),
                ),
            ],
            options={
                "db_table": "label_drug_key",
                "ordering": ["folded_string", "document"],
                "indexes": [
                    models.Index(fields=["folded_string"], name="label_drug_key_string_idx"),
                    models.Index(fields=["ingredient_rxcui"], name="label_drug_key_rxcui_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("folded_string", "document"), name="label_drug_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelSection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("boxed_warning", "Boxed warning"),
                            ("warnings", "Warnings"),
                            ("warnings_and_cautions", "Warnings and cautions"),
                            ("adverse_reactions", "Adverse reactions"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ordinal", models.IntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.labeldocument",
                    ),
                ),
            ],
            options={
                "db_table": "label_section",
                "ordering": ["document", "section_code", "ordinal"],
                "indexes": [models.Index(fields=["section_code"], name="label_section_code_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "section_code", "ordinal"), name="label_section_unique"
                    )
                ],
            },
        ),
    ]
