# Generated by Django 5.2.17 on 2026-09-06 18:31

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        # Created here rather than left to docker/postgres-init.sql. That file
        # runs once against the application database at initdb; a test database
        # is created fresh and never sees it, so the vector type would not exist
        # there. Idempotent, so running it against a database that already has
        # the extension does nothing.
        VectorExtension(),
        migrations.CreateModel(
            name="LabelChunk",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("boxed_warning", "Boxed warning"),
                            ("warnings", "Warnings"),
                            ("warnings_and_cautions", "Warnings and cautions"),
                            ("adverse_reactions", "Adverse reactions"),
                        ],
                        max_length=24,
                    ),
                ),
                ("text", models.TextField()),
                ("token_estimate", models.IntegerField()),
            ],
            options={
                "db_table": "label_chunk",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["section_code"], name="label_chunk_section_idx")],
            },
        ),
        migrations.CreateModel(
            name="ChunkEmbedding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=128)),
                ("model_revision", models.CharField(blank=True, default="", max_length=64)),
                ("dimensions", models.IntegerField()),
                ("vector", pgvector.django.vector.VectorField(dimensions=768)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="documents.labelchunk",
                    ),
                ),
            ],
            options={
                "db_table": "chunk_embedding",
                "ordering": ["chunk", "model"],
                "indexes": [
                    models.Index(fields=["model"], name="chunk_embedding_model_idx"),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=200,
                        fields=["vector"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "model"), name="chunk_embedding_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelChunkOccurrence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ordinal", models.IntegerField()),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="documents.labelchunk",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.labelsection",
                    ),
                ),
            ],
            options={
                "db_table": "label_chunk_occurrence",
                "ordering": ["section", "ordinal"],
                "indexes": [
                    models.Index(fields=["section", "ordinal"], name="label_chunk_occ_section_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chunk", "section"), name="label_chunk_occurrence_unique"
                    )
                ],
            },
        ),
    ]
