"""The CLI is the documented interface, so its shape is tested.

Unimplemented stages must fail loudly and say which roadmap prompt owns them;
``demo load`` must succeed on a repository that has no fixture slice yet,
because bootstrap runs it on a fresh clone.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import typer.main
from typer.core import TyperGroup
from typer.testing import CliRunner

from signaldesk import __version__
from signaldesk.cli import app

pytestmark = pytest.mark.unit

runner = CliRunner()


def test_help_lists_every_command_group() -> None:
    result = runner.invoke(app, ["--help"])
    assert result.exit_code == 0
    for group in ("ingest", "normalize", "signals", "index", "evals", "demo"):
        assert group in result.stdout


def test_version_prints_the_package_version() -> None:
    result = runner.invoke(app, ["version"])
    assert result.exit_code == 0
    assert result.stdout.strip() == __version__


@pytest.mark.parametrize(
    ("command", "prompt"),
    [
        (["ingest", "ctgov"], "P06"),
        (["ingest", "pubmed"], "P07"),
        (["normalize", "drugs"], "P03"),
    ],
)
def test_unimplemented_stage_names_its_roadmap_prompt(command: list[str], prompt: str) -> None:
    result = runner.invoke(app, command)
    assert result.exit_code != 0
    assert isinstance(result.exception, NotImplementedError)
    assert prompt in str(result.exception)


def test_implemented_signal_commands_are_listed() -> None:
    """The signal build is implemented, so it must no longer advertise a prompt."""
    result = runner.invoke(app, ["signals", "--help"])
    assert result.exit_code == 0
    for command in ("build", "artifact"):
        assert command in result.stdout


def test_implemented_ingest_commands_are_listed() -> None:
    """FAERS and SPL ingest are implemented, so they no longer advertise a prompt."""
    result = runner.invoke(app, ["ingest", "--help"])
    assert result.exit_code == 0
    for command in ("faers", "faers-dedup", "faers-status", "faers-quality", "labels"):
        assert command in result.stdout


def test_label_ingest_takes_a_scope_cap() -> None:
    """The first run is capped and measured rather than fetching every flagged
    string, so the cap has to be reachable from the command line.

    Read off the registered parameters rather than the rendered help. Typer
    renders help through Rich, which wraps to the terminal width and emits ANSI
    escapes, so a substring assertion against that text passes on a wide
    terminal and fails on a narrow one.
    """
    group = typer.main.get_command(app)
    assert isinstance(group, TyperGroup)
    ingest = group.commands["ingest"]
    assert isinstance(ingest, TyperGroup)
    options = {opt for param in ingest.commands["labels"].params for opt in param.opts}
    assert {"--top-k", "--run-id", "--force"} <= options


def test_cassette_recording_is_implemented_and_documented_as_live() -> None:
    """The one command that calls a provider. Its help has to say so, because
    everything else in the project runs offline and a reader will assume this
    does too."""
    result = runner.invoke(app, ["evals", "record-cassettes", "--help"])
    assert result.exit_code == 0
    assert not isinstance(result.exception, NotImplementedError)

    from signaldesk.cli import evals_record_cassettes

    # Whitespace-normalised: the docstring wraps, so a phrase can straddle a
    # line break and a naive substring check would miss it.
    doc = " ".join((evals_record_cassettes.__doc__ or "").split())
    assert "only command in this project that makes a live model call" in doc
    assert "never run by continuous integration" in doc
    assert "must be run by hand" in doc


def test_evals_run_reports_the_suite_it_cannot_run_yet() -> None:
    """A suite with no implementation still names the prompt that owns it."""
    result = runner.invoke(app, ["evals", "run", "briefs"])
    assert isinstance(result.exception, NotImplementedError)
    assert "briefs" in str(result.exception)


def test_the_retrieval_suite_refuses_rather_than_scoring_without_a_gold_set() -> None:
    """Implemented, and its implementation is a refusal.

    There is no gold set, so this exits non-zero naming the path and the schema.
    It must never exit zero, because a zero exit from an evaluation suite reads
    as a passing evaluation.
    """
    result = runner.invoke(app, ["evals", "run", "retrieval"])

    assert result.exit_code == 1
    assert "retrieval_v1.jsonl" in result.stderr
    assert "never generated by this project" in result.stderr


def test_the_implemented_index_commands_are_listed() -> None:
    """Chunking and the sparse index need no model, so they are here."""
    result = runner.invoke(app, ["index", "--help"])

    assert result.exit_code == 0
    for command in ("chunk", "sparse", "build"):
        assert command in result.stdout


@pytest.mark.parametrize("command", ["embed", "build", "benchmark"])
def test_the_model_commands_take_a_device(command: str) -> None:
    """Where a model runs is an argument, not something torch decides silently."""
    result = runner.invoke(app, ["index", command, "--help"])

    assert result.exit_code == 0
    assert "--device" in result.stdout
    for value in ("auto", "cpu", "cuda"):
        assert value in result.stdout


@pytest.mark.parametrize("command", ["embed", "build", "benchmark"])
def test_the_model_commands_take_a_precision_flag(command: str) -> None:
    """fp16 changes vector values, so it is opt-in and visible in --help."""
    result = runner.invoke(app, ["index", command, "--help"])

    assert result.exit_code == 0
    assert "--fp16" in result.stdout


def test_build_without_dense_still_runs_with_no_device_flags() -> None:
    """The existing invocation must not start failing because an option was added.

    --device defaults to auto, so a check that rejected any device option under
    --no-dense would reject this, which is how the whole chunk-and-sparse path
    would break on a change that never meant to touch it. This half passes on
    HEAD, where the option does not exist; it is here to pin the regression the
    other half could introduce.
    """
    result = runner.invoke(app, ["index", "build", "--no-dense", "--help"])

    assert result.exit_code == 0


def test_build_without_dense_rejects_an_explicitly_passed_device() -> None:
    """Silently ignoring it would leave a caller believing a device was chosen."""
    result = runner.invoke(app, ["index", "build", "--no-dense", "--device", "cpu"])

    assert result.exit_code == 1
    assert "--dense" in result.stderr


def test_demo_load_succeeds_when_the_fixture_directory_is_missing(tmp_path: Path) -> None:
    result = runner.invoke(app, ["demo", "load", "--fixtures", str(tmp_path / "absent")])
    assert result.exit_code == 0
    assert "nothing to load" in result.stdout


def test_demo_load_succeeds_when_only_a_placeholder_is_present(tmp_path: Path) -> None:
    (tmp_path / ".gitkeep").touch()
    result = runner.invoke(app, ["demo", "load", "--fixtures", str(tmp_path)])
    assert result.exit_code == 0
    assert "nothing to load" in result.stdout


def test_demo_load_counts_the_fixture_files_it_found(tmp_path: Path) -> None:
    (tmp_path / "cases.csv").write_text("primaryid\n1\n", encoding="utf-8")
    (tmp_path / "nested").mkdir()
    (tmp_path / "nested" / "reactions.csv").write_text("pt\nnausea\n", encoding="utf-8")

    result = runner.invoke(app, ["demo", "load", "--fixtures", str(tmp_path)])
    assert result.exit_code == 0
    assert "Found 2 fixture file(s)" in result.stdout
