"""Access to the published reference values the estimator tests are checked on.

``tests/fixtures/estimators/reference_values.json`` is generated by
``generate_reference_values.R`` in the same directory, which runs three
unmodified CRAN packages and writes out what they produce:

* ``epitools`` 0.5.10.1 - Wald odds ratio and risk ratio with 95 percent limits
* ``PhViD`` 1.0.8 - the BCPNN posterior, its variance and its 2.5th percentile
* ``openEBGM`` 0.9.1 - the gamma mixture fit and the posterior scores derived
  from it, on the CAERS data the package ships
* R 4.4.1 ``stats::chisq.test(correct = TRUE)`` - the Yates chi-squared

None of these numbers were computed by this project. That is the point: a golden
value worked out by hand alongside the code under test only confirms that the
code agrees with whatever the author believed while writing it.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

FIXTURE = Path(__file__).resolve().parents[2] / "fixtures" / "estimators" / "reference_values.json"


@pytest.fixture(scope="session")
def reference() -> dict[str, Any]:
    """The whole reference document."""
    document: dict[str, Any] = json.loads(FIXTURE.read_text(encoding="utf-8"))
    return document


@pytest.fixture(scope="session")
def reference_tables(reference: dict[str, Any]) -> list[dict[str, Any]]:
    """One entry per 2x2 table, with every estimator's reference value."""
    tables: list[dict[str, Any]] = reference["tables"]
    return tables


@pytest.fixture(scope="session")
def reference_mgps(reference: dict[str, Any]) -> dict[str, Any]:
    """The openEBGM fit, the data it was fitted on, and the scored sample."""
    mgps: dict[str, Any] = reference["mgps"]
    return mgps
